In [26]:
a = 5
b = 2
c = int( a / b)
print(c)

2


In [37]:
s = [1.,2.,5.]
import torch
st = torch.tensor(s)
print(st)

tensor([1., 2., 5.])


In [ ]:
st.std()
torch.std

tensor(2.0817)

In [41]:
t = torch.tensor([1,2,3,4,5])
a = t[2:4]
a -= 1
print(a)
print(t)

tensor([2, 3])
tensor([1, 2, 2, 3, 5])


In [60]:
a = torch.rand(3,1)
b = torch.rand(3,2)
z = a * b
y = b * a
print(z)
print(y)

tensor([[0.0271, 0.0209],
        [0.3147, 0.1879],
        [0.2248, 0.1565]])
tensor([[0.0271, 0.0209],
        [0.3147, 0.1879],
        [0.2248, 0.1565]])


In [57]:
a = torch.rand(2,3)
print(a)
b = torch.clip(a,0.2,0.8)
print(b)

tensor([[0.8828, 0.7401, 0.9267],
        [0.4080, 0.1045, 0.8612]])
tensor([[0.8000, 0.7401, 0.8000],
        [0.4080, 0.2000, 0.8000]])


In [58]:
torch.min(a,b)

tensor([[0.8000, 0.7401, 0.8000],
        [0.4080, 0.1045, 0.8000]])

In [62]:
advantages = torch.tensor([[-0.0164], [ 0.0164]])
old_log_probs = torch.tensor(
    [[ 3.8538,  2.9746,  1.8014, -4.2110, -1.5163,  2.1566,  1.6016,  3.3612, 0.7117, -1.3732],
    [-0.9867,  0.4830, -0.4632,  0.0835, -0.5032,  1.7197, -0.6195, -0.7914, 1.6068, -1.2432]])
policy_log_probs = torch.tensor(
    [[ 1.9269,  1.4873,  0.9007, -2.1055, -0.7581,  1.0783,  0.8008,  1.6806, 0.3559, -0.6866],
    [-0.4934,  0.2415, -0.2316,  0.0418, -0.2516,  0.8599, -0.3097, -0.3957, 0.8034, -0.6216]])

In [66]:
ratio = policy_log_probs / old_log_probs
ratio

tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5000, 0.5001,
         0.5000],
        [0.5001, 0.5000, 0.5000, 0.5006, 0.5000, 0.5000, 0.4999, 0.5000, 0.5000,
         0.5000]])

In [ ]:
clipped_ratio = ratio.clip(1-10.,1+10.)
res = - torch.min(ratio * advantages, clipped_ratio * advantages)
print(res)

In [67]:
from cs336_alignment.mygrpo import compute_policy_gradient_loss
compute_policy_gradient_loss(
    torch.tensor([]),
    "hi",
)

ValueError: 没有hi这种模式！

In [72]:
assert 1!=1, "?"

AssertionError: ?